#!/bin/bash
server=rhodes.tarantsov.com

set -xeuo pipefail
GOOS=linux GOARCH=amd64 go build -o /tmp/libroai-linux-amd64 .
scp /tmp/libroai-linux-amd64 "$server:~/"
ssh $server 'sudo ~/libroai-linux-amd64 -e prod -install'
