#!/bin/bash
server=rhodes.tarantsov.com

set -xeuo pipefail
GOOS=linux GOARCH=amd64 go build -o /tmp/buddyd-linux-amd64 .
scp /tmp/buddyd-linux-amd64 "$server:~/"
ssh $server 'sudo ~/buddyd-linux-amd64 -e prod -install'
